export interface rawHistoricBankData {
  start_time: string;
  end_time: string;
  address: string;
  symbol: string;
  name: string;
  group_address: string;
  mint: string;
  mint_decimals: number;
  usd_price: number | null;
  ts_total_asset_shares: string;
  ts_asset_share_value: string;
  ts_total_liability_shares: string;
  ts_liability_share_value: string;
  ts_deposit_limit: number;
  ts_borrow_limit: number;
  ts_collected_insurance_fees_outstanding: string;
  ts_collected_group_fees_outstanding: string;
  ts_asset_weight_init: string;
  ts_asset_weight_maint: string;
  ts_liability_weight_init: string;
  ts_liability_weight_maint: string;
  ts_optimal_utilization_rate: string;
  ts_plateau_interest_rate: string;
  ts_max_interest_rate: string;
  ts_insurance_fee_fixed_apr: string;
  ts_insurance_ir_fee: string;
  ts_protocol_fixed_fee_apr: string;
  ts_protocol_ir_fee: string;
  program_fee_fixed: string;
  program_fee_rate: string;
  ts_protocol_origination_fee: string;
  total_deposits: number;
  total_borrows: number;
  deposit_limit_ui: number;
  borrow_limit_ui: number;
  base_rate: number;
  utilization: number;
  deposit_rate: number;
  borrow_rate: number;
  deposit_rate_pct: number;
  borrow_rate_pct: number;
  total_deposits_usd: number | null;
  total_borrows_usd: number | null;
  deposit_limit_usd: number | null;
  borrow_limit_usd: number | null;
  insurance_fees_pending_usd: number | null;
  protocol_fees_pending_usd: number | null;
  vault_balance_usd: number | null;
  insurance_fees_collected_usd: number | null;
  protocol_fees_collected_usd: number | null;
  parsed_time: string;
  snapshot_slot: number | null;
  ts_bank_id: number;
  group_id: number;
  ts_raw_snapshot_id: number;
  ts_parse_version: number;
  token_program_address: string;
  ts_liquidity_vault: string;
  ts_liquidity_vault_bump: number;
  ts_liquidity_vault_authority_bump: number;
  ts_insurance_vault: string;
  ts_insurance_vault_bump: number;
  ts_insurance_vault_authority_bump: number;
  ts_fee_vault: string;
  ts_fee_vault_bump: number;
  ts_fee_vault_authority_bump: number;
  ts_last_update: number;
  ts_operational_state: number;
  ts_oracle_setup: number;
  ts_oracle_keys: string[];
  ts_risk_tier: number;
  ts_asset_tag: number;
  ts_total_asset_value_init_limit: number;
  ts_oracle_max_age: number;
  ts_flags: number;
  ts_emissions_rate: number;
  ts_emissions_remaining: string;
  ts_emissions_mint: string;
  ts_collected_program_fees_outstanding: string;
  ts_emode_tag: number;
  ts_emode_timestamp: number;
  ts_emode_flags: number;
  ts_emode_entries: unknown[];
  id: number;
}

export interface historicBankChartData {
  timestamp: string;
  borrowRate: number;
  depositRate: number;
  totalBorrows: number;
  totalDeposits: number;
  usdPrice: number;
  utilization: number;
  optimalUtilizationRate: number;
  baseRate: number;
  plateauInterestRate: number;
  maxInterestRate: number;
  insuranceIrFee: number;
  protocolIrFee: number;
  programFeeRate: number;
  insuranceFeeFixedApr: number;
  protocolFixedFeeApr: number;
}
